#page title
page_title                                : SwipeMath                                 # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6448857253                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : ch                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://sophiaedulabs.com/ios             # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://sophiaedulabs.com/android         # Enter Google Play Store URL.
discord_link                              : https://discord.gg/acHT82EBNG               # Enter Discord invite link.
#presskit_download_link                    : https://emilbaehr.com                    # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : SwipeMath                                 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price:
  en: Free
  de: Kostenlos
app_description:
  en: Math Exam coming up? Start swiping & Let the AI do the rest
  de: Mathe-Abi steht an? Fang an zu swipen & lass die KI den Rest machen

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Sophia Edu Labs                              
your_link                                 : https://swipemath.com                     
your_city                                 : Zurich                                
email_address                             : friedrich@sophiaedulabs.com
facebook_username                         :                                           
instagram_username                        : sophiadedulabs
twitter_username                          : swipemathai
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features:
  de:
    - title: Animierte Kurzvideos
      description: Wir haben animierte Kurzvideos erstellt, die das Lernen einfach und spaßig machen!
      fontawesome_icon_name: play-circle

    - title: Interaktive Übungen
      description: Unsere Übungen decken alles ab, du kannst sogar Beweise üben!
      fontawesome_icon_name: star

    - title: KI-generierter Lehrplan
      description: Nach einigen Interaktionen wird unsere KI dich kennenlernen und immer die richtigen Übungen für dich vorschlagen.
      fontawesome_icon_name: magic

  en:
    - title: Animated Short Videos
      description: We've created animated short videos that make learning easy and fun!
      fontawesome_icon_name: play-circle

    - title: Interactive Exercises
      description: Our exercises cover everything, you can even practice proofs!
      fontawesome_icon_name: star

    - title: AI-generated Curriculum
      description: After a few interactions, our AI will get to know you and always suggest just the right exercises for you.
      fontawesome_icon_name: magic

# Theme Settings
topbar_color                              : "#070c19"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#070c19"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#070c19"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ea594e"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#ea594e"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"








# SEO Plugin
title: SwipeMath App
tagline: Learn Math with Short Videos and AI. Download the SwipeMath App.
description: Math Exam coming up? Start swiping & Let the AI do the rest
url: https://swipemath.com
twitter:
  username: swipemathai
  card: summary
logo: /assets/logo.png
social:
  links:
    - https://twitter.com/swipemathai
    - https://linkedin.com/company/sophia-edu-labs
    - http://tiktok.com/@sophiaedulabs
    - https://instagram.com/sophiaedulabs



####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

languages: ["en", "de"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true
lang_from_path: true

repository: Sophia-Edu-Labs/swipemathlanding